image: docker:latest

services:
  - docker:dind

stages:
  - build
  - howitzer
  - upload
  - artifact_image

variables:
  GADGET_CONTAINER: ${CI_REGISTRY}/nextthingco/buildroot-development-container:testing
  HOWITZER_CONTAINER: ${CI_REGISTRY}/gadget/howitzer-container:master
  NAND_TYPE: Toshiba_512M_SLC
  UPLOAD_CONTAINER: ${CI_REGISTRY}/nextthingco/ci-tools:${GHVAR_UPLOAD_CONTAINER_BRANCH}
#  ARTIFACT_0: output/images/rootfs.ubi.sparse
#  ARTIFACT_1: output/images/spl-40000-1000-100.bin
#  ARTIFACT_2: output/images/uboot-40000.bin
#  ARTIFACT_3: output/images/uboot.script
  ARTIFACT_4: output/images/${CI_BUILD_REF_SLUG}-chip-pro-${CI_PROJECT_NAME}-b${CI_PIPELINE_ID}-${NAND_TYPE}.chp
  GHVAR_SLACK_CHANNEL: ${GHVAR_SLACK_CHANNEL}
  GHVAR_SLACK_HOOK: ${GHVAR_SLACK_HOOK}
  SSH_KEY_DIR: /root/.ssh/
  no_docker: "something"

build:
  image: ntc-registry.githost.io/nextthingco/buildroot-development-container:testing
  stage: build
  tags: [aws-auto-runner]
  script:
    - mkdir ${SSH_KEY_DIR}/
    - ssh-keyscan ntc.githost.io > ${SSH_KEY_DIR}/known_hosts
    - echo "${SSH_KEY_SECRET}" > ${SSH_KEY_DIR}/id_rsa
    - echo "${SSH_CONFIG}" > ${SSH_KEY_DIR}/ssh_config
    - chmod 0600 ${SSH_KEY_DIR}/*
#    - scripts/build-gadget make -s chippro_defconfig
#    - scripts/build-gadget make -s
    - make -s chippro_defconfig
    - make -s
    - ls /opt/output/images
    - mkdir -p output
    - mv /opt/output/images output/images
#    - tar -czf dlcache.tar.gz /opt/dlcache
#    - tar -czf build.tar.gz /opt/output/build
#    - tar -czf gadget-os-proto.tar.gz /opt/gadget-os-proto
#    - tar -czf local.tar.gz /local
#    - tar -czf tmp.tar.gz /tmp
  artifacts:
    expire_in: 20 minutes
    when: always
    paths:
      - output/images/*
#      - dlcache.tar.gz
#      - build.tar.gz
#      - gadget-os-proto.tar.gz
#      - local.tar.gz
#      - tmp.tar.gz

howitzer:
  image: ntc-registry.githost.io/gadget/howitzer-container:master
  stage: howitzer
  tags: [aws-auto-runner]
  dependencies:
    - build
  script:
    - ls output/images
    - /bin/bash -x scripts/flash-gadget
    - howitzer nand ${NAND_TYPE} chp fel.chp chp fastboot.chp -f ${ARTIFACT_4}
  artifacts:
    expire_in: 2 days
    when: always
    paths:
      - output/images/*

upload:
  image: ntc-registry.githost.io/nextthingco/ci-tools:unstable
  stage: upload
  tags: [aws-auto-runner]
  dependencies:
    - build
    - howitzer
  script:
    - ls -al
    - mkdir -p /upload
    - mv output /upload/output
    - cd /upload
    - ls -al /upload/output/images
    - ci-s3-upload ${ARTIFACT_4}
  artifacts:
    expire_in: 2 days
    when: always
    paths:
      - /upload/*

artifact_image:
  stage: artifact_image
  tags: [aws-auto-runner]
  script:
    - apk update && apk add git coreutils bash
    - docker login -u ${BUILDER_UN} -p ${BUILDER_PW}
    - /bin/bash -ex ./gen-dockerfiles.sh
